/**
 * Identifier generation.
 *
 * Internal primary keys are UUIDs generated by PostgreSQL. They are never the
 * identifier a customer sees: a booking link that exposed sequential or
 * structured ids would let anyone walk another tenant's appointments. Public
 * identifiers are therefore random, opaque and prefixed by entity type.
 */
import crypto from 'node:crypto';

/**
 * Crockford base32 without I, L, O and U — removes the character pairs people
 * mistype when reading an id off a screen or a confirmation email.
 */
const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

/**
 * Cryptographically secure random string over ALPHABET.
 *
 * Uses rejection sampling rather than `% ALPHABET.length`: the modulo of a
 * uniform byte over 32 happens to be uniform here, but the rejection loop keeps
 * the function correct if the alphabet is ever changed to a non-power-of-two.
 */
export function randomToken(length: number): string {
  const max = Math.floor(256 / ALPHABET.length) * ALPHABET.length;
  let out = '';
  while (out.length < length) {
    const bytes = crypto.randomBytes(length * 2);
    for (const byte of bytes) {
      if (byte >= max) continue;
      out += ALPHABET[byte % ALPHABET.length];
      if (out.length === length) break;
    }
  }
  return out;
}

/**
 * Public identifier for a customer-facing entity.
 *
 * 26 random characters ≈ 130 bits of entropy, so enumeration is infeasible even
 * with unlimited requests — rate limiting is defence in depth, not the only
 * barrier. The prefix makes support tickets and logs readable.
 */
export function publicId(prefix: string): string {
  return `${prefix}_${randomToken(26)}`;
}

export const newAppointmentPublicId = () => publicId('apt');
export const newParticipantPublicId = () => publicId('atn');
export const newCustomerPublicId = () => publicId('cus');
export const newWaitlistPublicId = () => publicId('wlt');

/** URL-safe secret for webhook signing. Shown to the operator exactly once. */
export function newWebhookSecret(): string {
  return `whsec_${crypto.randomBytes(32).toString('base64url')}`;
}

/** Opaque refresh token. Only its SHA-256 digest is ever persisted. */
export function newRefreshToken(): string {
  return crypto.randomBytes(48).toString('base64url');
}

/** Single-use token for email verification / password reset links. */
export function newVerificationToken(): string {
  return crypto.randomBytes(32).toString('base64url');
}

export function newUuid(): string {
  return crypto.randomUUID();
}

/**
 * URL slug from a display name. Deliberately conservative: ASCII-only, since a
 * slug ends up in a public URL and in a unique index.
 */
export function slugify(value: string): string {
  return (
    value
      .normalize('NFKD')
      // Strip combining marks so "Café" becomes "cafe" rather than losing the letter.
      .replace(/[\u0300-\u036f]/g, '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60)
      .replace(/-+$/g, '')
  );
}

/**
 * Slug guaranteed unique against `exists`, by appending -2, -3, … then falling
 * back to a random suffix so this can never loop unboundedly.
 */
export async function uniqueSlug(
  base: string,
  exists: (candidate: string) => Promise<boolean>,
): Promise<string> {
  const root = slugify(base) || 'item';
  if (!(await exists(root))) return root;

  for (let suffix = 2; suffix <= 50; suffix += 1) {
    const candidate = `${root}-${suffix}`;
    if (!(await exists(candidate))) return candidate;
  }
  return `${root}-${randomToken(6).toLowerCase()}`;
}

/** SHA-256 hex digest — used for token lookup columns and request hashing. */
export function sha256(value: string): string {
  return crypto.createHash('sha256').update(value).digest('hex');
}

/**
 * Constant-time comparison for secrets. A plain `===` on a token leaks its
 * prefix through timing.
 */
export function safeEqual(a: string, b: string): boolean {
  const bufferA = Buffer.from(a);
  const bufferB = Buffer.from(b);
  if (bufferA.length !== bufferB.length) return false;
  return crypto.timingSafeEqual(bufferA, bufferB);
}

/**
 * Stable digest of a request body, for idempotency-key conflict detection.
 * Object keys are sorted so logically identical payloads hash identically
 * regardless of JSON key order.
 */
export function canonicalHash(value: unknown): string {
  const canonical = (input: unknown): unknown => {
    if (Array.isArray(input)) return input.map(canonical);
    if (input && typeof input === 'object') {
      return Object.keys(input as Record<string, unknown>)
        .sort()
        .reduce<Record<string, unknown>>((acc, k) => {
          acc[k] = canonical((input as Record<string, unknown>)[k]);
          return acc;
        }, {});
    }
    return input;
  };
  return sha256(JSON.stringify(canonical(value)));
}
